set -g prefix M-a
unbind C-b
bind M-a send-prefix

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
