font_family GeistMono Nerd Font
font_size        13.0


# Appearance
window_padding_width 0
cursor_shape block
cursor_blink_interval 0
tab_bar_style hidden
hide_window_decorations no


# Scrollback
scrollback_lines 20000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER


# Mouse / Clipboard
detect_urls yes
url_style curly

copy_on_select no
open_url_with default


# Bell
enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no
bell_on_tab no


# Window behaviour
remember_window_size yes
placement_strategy top-left


# Shell integration
shell_integration enabled


# Performance / input
input_delay 2
repaint_delay 10
sync_to_monitor yes


# Tokyo Night
foreground              #c0caf5
background              #1a1b26

selection_foreground    #c0caf5
selection_background    #33467c

cursor                   #c0caf5
cursor_text_color        #1a1b26

url_color                #7aa2f7

active_border_color      #7aa2f7
inactive_border_color    #292e42
bell_border_color        #e0af68

color0   #15161e
color1   #f7768e
color2   #9ece6a
color3   #e0af68
color4   #7aa2f7
color5   #bb9af7
color6   #7dcfff
color7   #a9b1d6

color8   #414868
color9   #f7768e
color10  #9ece6a
color11  #e0af68
color12  #7aa2f7
color13  #bb9af7
color14  #7dcfff
color15  #c0caf5

background_opacity 0.90
dynamic_background_opacity yes

include themes/oled-tokyonight.conf
