hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
    hl.exec_cmd("swaync")
    hl.exec_cmd("systemctl --user start vicinae.service")
    hl.exec_cmd("qs -c oled")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --systemd QT_QPA_PLATFORM QT_QPA_PLATFORMTHEME XCURSOR_THEME XCURSOR_SIZE")
    hl.exec_cmd("hyprpaper")
end)
